export enum UserRole {
	STUDENT = 'STUDENT',
	LECTURER = 'LECTURER',
	SUPERUSER = 'SUPERUSER',
}

export enum AnswerReplyStatus {
	PENDING = 'PENDING',
	PARTLY_CORRECT = 'PARTLY_CORRECT',
	INCORRECT = 'INCORRECT',
	CORRECT = 'CORRECT',
}
