-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "health" SET DEFAULT 3,
ALTER COLUMN "rank" DROP NOT NULL,
ALTER COLUMN "rank" SET DEFAULT -1,
ALTER COLUMN "lastLogin" DROP NOT NULL,
ALTER COLUMN "groupId" DROP NOT NULL;
